[feature/OPT-885] to dev
iriusrisk/startleft pull request #321
Opened 2023-09-28 15:40 UTC by jmgarcia-iriusrisk

2023-10-02 08:38 UTC, smaneroiriusrisk requested changes
Just a few little changes about doc and help. Great feature, congrats!

2023-10-02 13:04 UTC, jmgarcia-iriusrisk commented
> Just a few little changes about doc and help. Great feature, congrats!

@smaneroiriusrisk great feedback! I have pushed all the changes requested

2023-10-03 06:01 UTC, smaneroiriusrisk approved these changes

2023-10-09 15:54 UTC, PacoCid approved these changes

2023-10-10 05:49 UTC, smaneroiriusrisk approved these changes

2023-10-10 07:26 UTC, merged