[OPT-580] to dev
iriusrisk/startleft pull request #93
Opened 2022-11-22 08:34 UTC by dantolin-iriusrisk

2022-11-22 13:33 UTC, daFont-iriusrisk approved these changes

2022-11-30 08:12 UTC, daFont-iriusrisk requested changes
There is a typo in workflow filename ~starleft-unit-integration~~ instead of startleft-unit-integration.

2022-11-30 08:16 UTC, dantolin-iriusrisk commented
> There is a typo in workflow filename ~starleft-unit-integration~ instead of startleft-unit-integration.

Done!

2022-11-30 08:16 UTC, daFont-iriusrisk approved these changes

2022-11-30 08:32 UTC, merged